# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

formatter:
    page_width: 120

linter:
    rules:
        avoid_print: true
        prefer_single_quotes: true

        sort_child_properties_last: true
        sort_constructors_first: true
        sort_pub_dependencies: true
